export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const REQUESTS_ROUTE = '/requests'
export const SCHEDULE_ROUTE = '/schedule'
